package com.app.Benefits_of_Java;

public class Benefits_of_Java {
    //JAVA OFRECE BARIOS BENEFICIOS, UNO DE LOS PRINCIPALES ES LA PROGRAMACION ORIENTADA A OBJETOS (POO)
    //ESO SIGNFICA QUE TODO EL CODIGO SE DEFINE EN CLASES Y QUE EN SU MAYORÍA PUEDEN INSTANCIARSE EN OBJETOS
    // TAMBIÉN OFRECE OTRO ENFOQUE QUE ES LA PROGRAMACIÓN FUNCIONAL, PERO LA PRINCIPAL ES POO.

    //OTRO BENEFICIO ES DE ACUERDO A UNO DE LOS PILARES DE POO, QUE ES LA ENCAPSULACIÓN, QUE ES QUE JAVA OFRECE MODIFICADORES DE ACCESO
    //QUE PROTEGEN EL USO O MODIFICACIÓN DE LOS DATOS

    //JAVA ES UN LENGUAJE INTERPRETADO YA QUE SE COMPILA A BYTECODE

    //ROBUSTEZ: JAVA PREVIENE LAS FUGAS DE MEMORIA, GESTIONA POR SÍ MISMO SU MEMORIA Y REALIZA LA RECOLECCIÓN DE BASURA AUTOMATICAMENTE

    //SEGURIDAD: EL CODIGO JAVA SE EJECUTA DENTRO DE LA JVM, ESTO CREA UNA CAJA DE SEGURIDAD.

}
